
export namespace HousingLandSetIndexNS {
  export type HousingLandSetIndex = {
    Pagination: Pagination;
    Results:    Result[];
  }
  
  export type Pagination = {
    Page:           number;
    PageNext:       number;
    PagePrev:       number;
    PageTotal:      number;
    Results:        number;
    ResultsPerPage: number;
    ResultsTotal:   number;
  }
  
  export type Result = {
    ID:   number;
    Icon: null;
    Name: null;
    Url:  string;
  }
  
}

export type Index = HousingLandSetIndexNS.HousingLandSetIndex;

export namespace HousingLandSetNS {
  export type HousingLandSet = {
    GameContentLinks: any[];
    ID:               number;
    InitialPrice0:    number;
    InitialPrice1:    number;
    InitialPrice10:   number;
    InitialPrice11:   number;
    InitialPrice12:   number;
    InitialPrice13:   number;
    InitialPrice14:   number;
    InitialPrice15:   number;
    InitialPrice16:   number;
    InitialPrice17:   number;
    InitialPrice18:   number;
    InitialPrice19:   number;
    InitialPrice2:    number;
    InitialPrice20:   number;
    InitialPrice21:   number;
    InitialPrice22:   number;
    InitialPrice23:   number;
    InitialPrice24:   number;
    InitialPrice25:   number;
    InitialPrice26:   number;
    InitialPrice27:   number;
    InitialPrice28:   number;
    InitialPrice29:   number;
    InitialPrice3:    number;
    InitialPrice30:   number;
    InitialPrice31:   number;
    InitialPrice32:   number;
    InitialPrice33:   number;
    InitialPrice34:   number;
    InitialPrice35:   number;
    InitialPrice36:   number;
    InitialPrice37:   number;
    InitialPrice38:   number;
    InitialPrice39:   number;
    InitialPrice4:    number;
    InitialPrice40:   number;
    InitialPrice41:   number;
    InitialPrice42:   number;
    InitialPrice43:   number;
    InitialPrice44:   number;
    InitialPrice45:   number;
    InitialPrice46:   number;
    InitialPrice47:   number;
    InitialPrice48:   number;
    InitialPrice49:   number;
    InitialPrice5:    number;
    InitialPrice50:   number;
    InitialPrice51:   number;
    InitialPrice52:   number;
    InitialPrice53:   number;
    InitialPrice54:   number;
    InitialPrice55:   number;
    InitialPrice56:   number;
    InitialPrice57:   number;
    InitialPrice58:   number;
    InitialPrice59:   number;
    InitialPrice6:    number;
    InitialPrice7:    number;
    InitialPrice8:    number;
    InitialPrice9:    number;
    MinPrice0:        number;
    MinPrice1:        number;
    MinPrice10:       number;
    MinPrice11:       number;
    MinPrice12:       number;
    MinPrice13:       number;
    MinPrice14:       number;
    MinPrice15:       number;
    MinPrice16:       number;
    MinPrice17:       number;
    MinPrice18:       number;
    MinPrice19:       number;
    MinPrice2:        number;
    MinPrice20:       number;
    MinPrice21:       number;
    MinPrice22:       number;
    MinPrice23:       number;
    MinPrice24:       number;
    MinPrice25:       number;
    MinPrice26:       number;
    MinPrice27:       number;
    MinPrice28:       number;
    MinPrice29:       number;
    MinPrice3:        number;
    MinPrice30:       number;
    MinPrice31:       number;
    MinPrice32:       number;
    MinPrice33:       number;
    MinPrice34:       number;
    MinPrice35:       number;
    MinPrice36:       number;
    MinPrice37:       number;
    MinPrice38:       number;
    MinPrice39:       number;
    MinPrice4:        number;
    MinPrice40:       number;
    MinPrice41:       number;
    MinPrice42:       number;
    MinPrice43:       number;
    MinPrice44:       number;
    MinPrice45:       number;
    MinPrice46:       number;
    MinPrice47:       number;
    MinPrice48:       number;
    MinPrice49:       number;
    MinPrice5:        number;
    MinPrice50:       number;
    MinPrice51:       number;
    MinPrice52:       number;
    MinPrice53:       number;
    MinPrice54:       number;
    MinPrice55:       number;
    MinPrice56:       number;
    MinPrice57:       number;
    MinPrice58:       number;
    MinPrice59:       number;
    MinPrice6:        number;
    MinPrice7:        number;
    MinPrice8:        number;
    MinPrice9:        number;
    Patch:            null;
    PlotSize0:        number;
    PlotSize1:        number;
    PlotSize10:       number;
    PlotSize11:       number;
    PlotSize12:       number;
    PlotSize13:       number;
    PlotSize14:       number;
    PlotSize15:       number;
    PlotSize16:       number;
    PlotSize17:       number;
    PlotSize18:       number;
    PlotSize19:       number;
    PlotSize2:        number;
    PlotSize20:       number;
    PlotSize21:       number;
    PlotSize22:       number;
    PlotSize23:       number;
    PlotSize24:       number;
    PlotSize25:       number;
    PlotSize26:       number;
    PlotSize27:       number;
    PlotSize28:       number;
    PlotSize29:       number;
    PlotSize3:        number;
    PlotSize30:       number;
    PlotSize31:       number;
    PlotSize32:       number;
    PlotSize33:       number;
    PlotSize34:       number;
    PlotSize35:       number;
    PlotSize36:       number;
    PlotSize37:       number;
    PlotSize38:       number;
    PlotSize39:       number;
    PlotSize4:        number;
    PlotSize40:       number;
    PlotSize41:       number;
    PlotSize42:       number;
    PlotSize43:       number;
    PlotSize44:       number;
    PlotSize45:       number;
    PlotSize46:       number;
    PlotSize47:       number;
    PlotSize48:       number;
    PlotSize49:       number;
    PlotSize5:        number;
    PlotSize50:       number;
    PlotSize51:       number;
    PlotSize52:       number;
    PlotSize53:       number;
    PlotSize54:       number;
    PlotSize55:       number;
    PlotSize56:       number;
    PlotSize57:       number;
    PlotSize58:       number;
    PlotSize59:       number;
    PlotSize6:        number;
    PlotSize7:        number;
    PlotSize8:        number;
    PlotSize9:        number;
    Url:              string;
  }
  
}

export type HousingLandSet = HousingLandSetNS.HousingLandSet;
