export interface QuestRedoIndex {
  Pagination: Pagination;
  Results:    Result[];
}

export interface Pagination {
  Page:           number;
  PageNext:       number;
  PagePrev:       number;
  PageTotal:      number;
  Results:        number;
  ResultsPerPage: number;
  ResultsTotal:   number;
}

export interface Result {
  ID:   number;
  Icon: null;
  Name: null;
  Url:  string;
}


export interface QuestRedo1 {
  Chapter:            Chapter;
  ChapterTarget:      string;
  ChapterTargetID:    number;
  FinalQuest:         { [key: string]: number | { [key: string]: FinalQuestClass | number | string } | null | string };
  FinalQuestTarget:   string;
  FinalQuestTargetID: number;
  GameContentLinks:   any[];
  ID:                 number;
  Patch:              null;
  Quest0:             { [key: string]: number | { [key: string]: Quest0Class | number | null | string } | null | string };
  Quest0Target:       string;
  Quest0TargetID:     number;
  Quest1:             { [key: string]: number | { [key: string]: Quest1Class | number | null | string } | null | string };
  Quest10:            { [key: string]: number | { [key: string]: Quest10Class | number | null | string } | null | string };
  Quest10Target:      string;
  Quest10TargetID:    number;
  Quest11:            { [key: string]: number | { [key: string]: Quest0Class | number | null | string } | null | string };
  Quest11Target:      string;
  Quest11TargetID:    number;
  Quest12:            { [key: string]: number | { [key: string]: Quest0Class | number | null | string } | null | string };
  Quest12Target:      string;
  Quest12TargetID:    number;
  Quest13:            { [key: string]: number | { [key: string]: Quest0Class | number | null | string } | null | string };
  Quest13Target:      string;
  Quest13TargetID:    number;
  Quest14:            { [key: string]: number | { [key: string]: Quest1Class | number | null | string } | null | string };
  Quest14Target:      string;
  Quest14TargetID:    number;
  Quest15:            { [key: string]: number | { [key: string]: Quest15Class | number | string } | null | string };
  Quest15Target:      string;
  Quest15TargetID:    number;
  Quest16:            { [key: string]: number | { [key: string]: Quest16Class | number | string } | null | string };
  Quest16Target:      string;
  Quest16TargetID:    number;
  Quest17:            { [key: string]: number | { [key: string]: Quest17Class | number | string } | null | string };
  Quest17Target:      string;
  Quest17TargetID:    number;
  Quest18:            { [key: string]: number | { [key: string]: Quest16Class | number | string } | null | string };
  Quest18Target:      string;
  Quest18TargetID:    number;
  Quest19:            { [key: string]: number | { [key: string]: Quest19Class | number | string } | null | string };
  Quest19Target:      string;
  Quest19TargetID:    number;
  Quest1Target:       string;
  Quest1TargetID:     number;
  Quest2:             { [key: string]: number | { [key: string]: Quest2Class | number | null | string } | null | string };
  Quest20:            { [key: string]: number | { [key: string]: Quest16Class | number | string } | null | string };
  Quest20Target:      string;
  Quest20TargetID:    number;
  Quest21:            null;
  Quest21Target:      string;
  Quest21TargetID:    number;
  Quest22:            null;
  Quest22Target:      string;
  Quest22TargetID:    number;
  Quest23:            null;
  Quest23Target:      string;
  Quest23TargetID:    number;
  Quest24:            null;
  Quest24Target:      string;
  Quest24TargetID:    number;
  Quest25:            null;
  Quest25Target:      string;
  Quest25TargetID:    number;
  Quest26:            null;
  Quest26Target:      string;
  Quest26TargetID:    number;
  Quest27:            null;
  Quest27Target:      string;
  Quest27TargetID:    number;
  Quest28:            null;
  Quest28Target:      string;
  Quest28TargetID:    number;
  Quest29:            null;
  Quest29Target:      string;
  Quest29TargetID:    number;
  Quest2Target:       string;
  Quest2TargetID:     number;
  Quest3:             { [key: string]: number | { [key: string]: Quest15Class | number | string } | null | string };
  Quest30:            null;
  Quest30Target:      string;
  Quest30TargetID:    number;
  Quest31:            null;
  Quest31Target:      string;
  Quest31TargetID:    number;
  Quest3Target:       string;
  Quest3TargetID:     number;
  Quest4:             { [key: string]: number | { [key: string]: Quest4Class | number | null | string } | null | string };
  Quest4Target:       string;
  Quest4TargetID:     number;
  Quest5:             { [key: string]: number | { [key: string]: Quest0Class | number | null | string } | null | string };
  Quest5Target:       string;
  Quest5TargetID:     number;
  Quest6:             { [key: string]: number | { [key: string]: Quest1Class | number | null | string } | null | string };
  Quest6Target:       string;
  Quest6TargetID:     number;
  Quest7:             { [key: string]: number | { [key: string]: Quest7Class | number | null | string } | null | string };
  Quest7Target:       string;
  Quest7TargetID:     number;
  Quest8:             { [key: string]: number | { [key: string]: Quest0Class | number | null | string } | null | string };
  Quest8Target:       string;
  Quest8TargetID:     number;
  Quest9:             { [key: string]: number | { [key: string]: Quest0Class | number | null | string } | null | string };
  Quest9Target:       string;
  Quest9TargetID:     number;
  Url:                string;
}

export interface Chapter {
  ID: number;
}

export interface FinalQuestClass {
  DataType?:              number;
  ID:                     number;
  JournalSection?:        number;
  Name?:                  string;
  Name_de?:               string;
  Name_en?:               string;
  Name_fr?:               string;
  Name_ja?:               string;
  SeparateType?:          number;
  DiscoveryArrayByte?:    number;
  DiscoveryFlag?:         number;
  DiscoveryIndex?:        number | string;
  Hierarchy?:             number;
  IsEvent?:               number;
  MapCondition?:          number;
  MapFilename?:           string;
  MapFilenameId?:         string;
  MapIndex?:              number;
  MapMarkerRange?:        number;
  OffsetX?:               number;
  OffsetY?:               number;
  PlaceName?:             number;
  PlaceNameRegion?:       number;
  PlaceNameSub?:          number;
  PriorityCategoryUI?:    number;
  PriorityUI?:            number;
  SizeFactor?:            number;
  TerritoryType?:         number;
  AchievementIndex?:      number | string;
  "AddedIn5-3"?:          number;
  Aetheryte?:             number;
  ArrayEventHandler?:     number;
  BGM?:                   number;
  BattalionMode?:         number;
  Bg?:                    string;
  Bg_en?:                 string;
  ExVersion?:             number;
  ExclusiveType?:         number;
  FixedTime?:             string;
  IsPvpZone?:             number;
  LoadingImage?:          number;
  Map?:                   number;
  Mount?:                 number;
  MountSpeed?:            number;
  PCSearch?:              number;
  PlaceNameIcon?:         string;
  PlaceNameIconID?:       number | string;
  PlaceNameRegionIcon?:   string;
  PlaceNameRegionIconID?: number | string;
  PlaceNameZone?:         number;
  QuestBattle?:           number;
  Resident?:              number;
  Stealth?:               number;
  TerritoryIntendedUse?:  number;
  WeatherRate?:           number;
}

export interface Quest0Class {
  "1HWpn%"?:                   number;
  "2HWpn%"?:                   number;
  "Bracelet%"?:                number;
  "Chest%"?:                   number;
  "ChestHead%"?:               number;
  "ChestHeadLegsFeet%"?:       number;
  "ChestLegsFeet%"?:           number;
  "ChestLegsGloves%"?:         number;
  Description?:                string;
  Description_de?:             string;
  Description_en?:             string;
  Description_fr?:             string;
  Description_ja?:             string;
  "Earring%"?:                 number;
  "Feet%"?:                    number;
  "Hands%"?:                   number;
  "Head%"?:                    number;
  "HeadChestHandsLegsFeet%"?:  number;
  ID:                          number;
  "Legs%"?:                    number;
  "LegsFeet%"?:                number;
  MeldParam0?:                 number;
  MeldParam1?:                 number;
  MeldParam10?:                number;
  MeldParam11?:                number;
  MeldParam12?:                number;
  MeldParam2?:                 number;
  MeldParam3?:                 number;
  MeldParam4?:                 number;
  MeldParam5?:                 number;
  MeldParam6?:                 number;
  MeldParam7?:                 number;
  MeldParam8?:                 number;
  MeldParam9?:                 number;
  Name?:                       string;
  Name_de?:                    string;
  Name_en?:                    string;
  Name_fr?:                    string;
  Name_ja?:                    string;
  "Necklace%"?:                number;
  "OH%"?:                      number;
  OrderPriority?:              number;
  PacketIndex?:                number;
  "Ring%"?:                    number;
  "UnderArmor%"?:              number;
  "Waist%"?:                   number;
  ACN?:                        number;
  ADV?:                        number;
  ALC?:                        number;
  ARC?:                        number;
  ARM?:                        number;
  AST?:                        number;
  BLM?:                        number;
  BLU?:                        number;
  BRD?:                        number;
  BSM?:                        number;
  BTN?:                        number;
  CNJ?:                        number;
  CRP?:                        number;
  CUL?:                        number;
  DNC?:                        number;
  DRG?:                        number;
  DRK?:                        number;
  FSH?:                        number;
  GLA?:                        number;
  GNB?:                        number;
  GSM?:                        number;
  LNC?:                        number;
  LTW?:                        number;
  MCH?:                        number;
  MIN?:                        number;
  MNK?:                        number;
  MRD?:                        number;
  NIN?:                        number;
  PGL?:                        number;
  PLD?:                        number;
  RDM?:                        number;
  ROG?:                        number;
  SAM?:                        number;
  SCH?:                        number;
  SMN?:                        number;
  THM?:                        number;
  WAR?:                        number;
  WHM?:                        number;
  WVR?:                        number;
  Abbreviation?:               Abbreviation;
  Abbreviation_de?:            AbbreviationDe;
  Abbreviation_en?:            Abbreviation;
  Abbreviation_fr?:            AbbreviationFr;
  Abbreviation_ja?:            Abbreviation;
  BattleClassIndex?:           string;
  CanQueueForDuty?:            number;
  ClassJobCategory?:           number;
  ClassJobParent?:             number;
  ExpArrayIndex?:              number;
  Icon?:                       string;
  IsLimitedJob?:               number;
  ItemSoulCrystal?:            number;
  ItemStartingWeapon?:         number;
  JobIndex?:                   number;
  LimitBreak1?:                number;
  LimitBreak2?:                number;
  LimitBreak3?:                number;
  ModifierDexterity?:          number;
  ModifierHitPoints?:          number;
  ModifierIntelligence?:       number;
  ModifierManaPoints?:         number;
  ModifierMind?:               number;
  ModifierPiety?:              number;
  ModifierStrength?:           number;
  ModifierVitality?:           number;
  MonsterNote?:                number;
  NameEnglish?:                NameEnglish;
  NameEnglish_de?:             NameEnglish;
  NameEnglish_en?:             NameEnglish;
  NameEnglish_fr?:             NameEnglish;
  NameEnglish_ja?:             NameEnglish;
  PartyBonus?:                 number;
  Prerequisite?:               number;
  PrimaryStat?:                number;
  RelicQuest?:                 number;
  Role?:                       number;
  StartingLevel?:              number;
  StartingTown?:               number;
  UIPriority?:                 number;
  UnlockQuest?:                number;
  Body?:                       number;
  Ears?:                       number;
  Feet?:                       number;
  FingerL?:                    number;
  FingerR?:                    number;
  Gloves?:                     number;
  Head?:                       number;
  Legs?:                       number;
  MainHand?:                   number;
  Neck?:                       number;
  OffHand?:                    number;
  SoulCrystal?:                number;
  Waist?:                      number;
  Wrists?:                     number;
  AdditionalData?:             number;
  Adjective?:                  number;
  AetherialReduce?:            number;
  AlwaysCollectable?:          number;
  Article?:                    number;
  BaseParam0?:                 number;
  BaseParam1?:                 number;
  BaseParam2?:                 number;
  BaseParam3?:                 number;
  BaseParam4?:                 number;
  BaseParam5?:                 number;
  BaseParamModifier?:          number;
  BaseParamSpecial0?:          number;
  BaseParamSpecial1?:          number;
  BaseParamSpecial2?:          number;
  BaseParamSpecial3?:          number;
  BaseParamSpecial4?:          number;
  BaseParamSpecial5?:          number;
  BaseParamValue0?:            number;
  BaseParamValue1?:            number;
  BaseParamValue2?:            number;
  BaseParamValue3?:            number;
  BaseParamValue4?:            number;
  BaseParamValue5?:            number;
  BaseParamValueSpecial0?:     number;
  BaseParamValueSpecial1?:     number;
  BaseParamValueSpecial2?:     number;
  BaseParamValueSpecial3?:     number;
  BaseParamValueSpecial4?:     number;
  BaseParamValueSpecial5?:     number;
  Block?:                      number;
  BlockRate?:                  number;
  CanBeHq?:                    number;
  ClassJobRepair?:             number;
  ClassJobUse?:                number;
  CooldownS?:                  number;
  DamageMag?:                  number;
  DamagePhys?:                 number;
  DefenseMag?:                 number;
  DefensePhys?:                number;
  DelayMs?:                    number;
  Desynth?:                    number;
  EquipRestriction?:           number;
  EquipSlotCategory?:          number;
  FilterGroup?:                number;
  GrandCompany?:               number;
  IconID?:                     number;
  IsAdvancedMeldingPermitted?: number;
  IsCollectable?:              number;
  IsCrestWorthy?:              number;
  IsDyeable?:                  number;
  IsGlamourous?:               number;
  IsIndisposable?:             number;
  IsPvP?:                      number;
  IsUnique?:                   number;
  IsUntradable?:               number;
  ItemAction?:                 number;
  ItemGlamour?:                number;
  ItemRepair?:                 number;
  ItemSearchCategory?:         number;
  ItemSeries?:                 number;
  ItemSortCatgegory?:          number;
  ItemSpecialBonus?:           number;
  ItemSpecialBonusParam?:      number;
  ItemUICategory?:             number;
  LevelEquip?:                 number;
  LevelItem?:                  number;
  Lot?:                        number;
  MateriaSlotCount?:           number;
  MaterializeType?:            number;
  ModelMain?:                  Model;
  ModelSub?:                   Model;
  Plural?:                     Plural;
  Plural_de?:                  PluralDe;
  Plural_en?:                  Plural;
  Plural_fr?:                  PluralFr;
  Plural_ja?:                  string;
  PossessivePronoun?:          number;
  PriceLow?:                   number;
  PriceMid?:                   number;
  Pronoun?:                    number;
  Rarity?:                     number;
  Singular?:                   Singular;
  Singular_de?:                SingularDe;
  Singular_en?:                Singular;
  Singular_fr?:                SingularFr;
  Singular_ja?:                SingularJa;
  StackSize?:                  number;
  StartsWithVowel?:            number;
  Category?:                   number;
  ClassJob?:                   number;
  Order?:                      number;
  OrderMajor?:                 number;
  OrderMinor?:                 number;
  DataType?:                   number;
  JournalSection?:             number;
  SeparateType?:               number;
  DiscoveryArrayByte?:         number;
  DiscoveryFlag?:              number;
  DiscoveryIndex?:             number;
  Hierarchy?:                  number;
  IsEvent?:                    number;
  MapCondition?:               number;
  MapFilename?:                MapFilename;
  MapFilenameId?:              MapFilenameID;
  MapIndex?:                   number;
  MapMarkerRange?:             number;
  OffsetX?:                    number;
  OffsetY?:                    number;
  PlaceName?:                  number;
  PlaceNameRegion?:            number;
  PlaceNameSub?:               number;
  PriorityCategoryUI?:         number;
  PriorityUI?:                 number;
  SizeFactor?:                 number;
  TerritoryType?:              number;
  AchievementIndex?:           number;
  "AddedIn5-3"?:               number;
  Aetheryte?:                  number;
  ArrayEventHandler?:          number;
  BGM?:                        number;
  BattalionMode?:              number;
  Bg?:                         Bg;
  Bg_en?:                      Bg;
  ExVersion?:                  number;
  ExclusiveType?:              number;
  FixedTime?:                  string;
  IsPvpZone?:                  number;
  LoadingImage?:               number;
  Map?:                        number;
  Mount?:                      number;
  MountSpeed?:                 number;
  PCSearch?:                   number;
  PlaceNameIcon?:              PlaceNameIcon;
  PlaceNameIconID?:            number;
  PlaceNameRegionIcon?:        Quest0PlaceNameRegionIcon;
  PlaceNameRegionIconID?:      number;
  PlaceNameZone?:              number;
  QuestBattle?:                number;
  Resident?:                   number;
  Stealth?:                    number;
  TerritoryIntendedUse?:       number;
  WeatherRate?:                number;
}

export enum Abbreviation {
  GSM = "GSM",
  Ltw = "LTW",
  Wvr = "WVR",
}

export enum AbbreviationDe {
  Ger = "GER",
  Gld = "GLD",
  Web = "WEB",
}

export enum AbbreviationFr {
  Cou = "COU",
  Orf = "ORF",
  Tan = "TAN",
}

export enum Bg {
  FfxivSeaS1FldS1F1LevelS1F1 = "ffxiv/sea_s1/fld/s1f1/level/s1f1",
  FfxivSeaS1FldS1F2LevelS1F2 = "ffxiv/sea_s1/fld/s1f2/level/s1f2",
  FfxivSeaS1FldS1F4LevelS1F4 = "ffxiv/sea_s1/fld/s1f4/level/s1f4",
}

export enum MapFilename {
  MS1F1S1F100Jpg = "/m/s1f1/s1f1.00.jpg",
  MS1F2S1F200Jpg = "/m/s1f2/s1f2.00.jpg",
  MS1F4S1F400Jpg = "/m/s1f4/s1f4.00.jpg",
}

export enum MapFilenameID {
  S1F100 = "s1f1/00",
  S1F200 = "s1f2/00",
  S1F400 = "s1f4/00",
}

export enum Model {
  The0000 = "0, 0, 0, 0",
}

export enum NameEnglish {
  Goldsmith = "Goldsmith",
  Leatherworker = "Leatherworker",
  Weaver = "Weaver",
}

export enum PlaceNameIcon {
  I123000123004PNG = "/i/123000/123004.png",
  I123000123005PNG = "/i/123000/123005.png",
  I123000123007PNG = "/i/123000/123007.png",
}

export enum Quest0PlaceNameRegionIcon {
  I122000122001PNG = "/i/122000/122001.png",
}

export enum Plural {
  FragmentsOfGrade1DarkMatter = "fragments of grade 1 dark matter",
  FragmentsOfGrade2DarkMatter = "fragments of grade 2 dark matter",
  GlamourPrisms = "glamour prisms",
}

export enum PluralDe {
  Projektionsprismen = "Projektionsprismen",
  QuantenPGrad1Dunkelmaterie = "Quanten[p] Grad 1 Dunkelmaterie",
  QuantenPGrad2Dunkelmaterie = "Quanten[p] Grad 2 Dunkelmaterie",
}

export enum PluralFr {
  FragmentsDeMatièreSombreGradeI = "fragments de matière sombre grade I",
  FragmentsDeMatièreSombreGradeII = "fragments de matière sombre grade II",
  PrismesMirage = "prismes mirage",
}

export enum Singular {
  FragmentOfGrade1DarkMatter = "fragment of grade 1 dark matter",
  FragmentOfGrade2DarkMatter = "fragment of grade 2 dark matter",
  GlamourPrism = "glamour prism",
}

export enum SingularDe {
  Projektionsprisma = "Projektionsprisma",
  QuantumPGrad1Dunkelmaterie = "Quantum[p] Grad 1 Dunkelmaterie",
  QuantumPGrad2Dunkelmaterie = "Quantum[p] Grad 2 Dunkelmaterie",
}

export enum SingularFr {
  FragmentDeMatièreSombreGradeI = "fragment de matière sombre grade I",
  FragmentDeMatièreSombreGradeII = "fragment de matière sombre grade II",
  PrismeMirage = "prisme mirage",
}

export enum SingularJa {
  ダークマターG1 = "ダークマターG1",
  ダークマターG2 = "ダークマターG2",
  ミラージュプリズム = "ミラージュプリズム",
}

export interface Quest1Class {
  "1HWpn%"?:                   number;
  "2HWpn%"?:                   number;
  "Bracelet%"?:                number;
  "Chest%"?:                   number;
  "ChestHead%"?:               number;
  "ChestHeadLegsFeet%"?:       number;
  "ChestLegsFeet%"?:           number;
  "ChestLegsGloves%"?:         number;
  Description?:                string;
  Description_de?:             string;
  Description_en?:             string;
  Description_fr?:             string;
  Description_ja?:             string;
  "Earring%"?:                 number;
  "Feet%"?:                    number;
  "Hands%"?:                   number;
  "Head%"?:                    number;
  "HeadChestHandsLegsFeet%"?:  number;
  ID:                          number;
  "Legs%"?:                    number;
  "LegsFeet%"?:                number;
  MeldParam0?:                 number;
  MeldParam1?:                 number;
  MeldParam10?:                number;
  MeldParam11?:                number;
  MeldParam12?:                number;
  MeldParam2?:                 number;
  MeldParam3?:                 number;
  MeldParam4?:                 number;
  MeldParam5?:                 number;
  MeldParam6?:                 number;
  MeldParam7?:                 number;
  MeldParam8?:                 number;
  MeldParam9?:                 number;
  Name?:                       string;
  Name_de?:                    string;
  Name_en?:                    string;
  Name_fr?:                    string;
  Name_ja?:                    string;
  "Necklace%"?:                number;
  "OH%"?:                      number;
  OrderPriority?:              number;
  PacketIndex?:                number | string;
  "Ring%"?:                    number;
  "UnderArmor%"?:              number;
  "Waist%"?:                   number;
  ACN?:                        number;
  ADV?:                        number;
  ALC?:                        number;
  ARC?:                        number;
  ARM?:                        number;
  AST?:                        number;
  BLM?:                        number;
  BLU?:                        number;
  BRD?:                        number;
  BSM?:                        number;
  BTN?:                        number;
  CNJ?:                        number;
  CRP?:                        number;
  CUL?:                        number;
  DNC?:                        number;
  DRG?:                        number;
  DRK?:                        number;
  FSH?:                        number;
  GLA?:                        number;
  GNB?:                        number;
  GSM?:                        number;
  LNC?:                        number;
  LTW?:                        number;
  MCH?:                        number;
  MIN?:                        number;
  MNK?:                        number;
  MRD?:                        number;
  NIN?:                        number;
  PGL?:                        number;
  PLD?:                        number;
  RDM?:                        number;
  ROG?:                        number;
  SAM?:                        number;
  SCH?:                        number;
  SMN?:                        number;
  THM?:                        number;
  WAR?:                        number;
  WHM?:                        number;
  WVR?:                        number;
  Abbreviation?:               string;
  Abbreviation_de?:            string;
  Abbreviation_en?:            string;
  Abbreviation_fr?:            string;
  Abbreviation_ja?:            string;
  BattleClassIndex?:           number | string;
  CanQueueForDuty?:            number;
  ClassJobCategory?:           number;
  ClassJobParent?:             number;
  ExpArrayIndex?:              number;
  Icon?:                       string;
  IsLimitedJob?:               number;
  ItemSoulCrystal?:            number;
  ItemStartingWeapon?:         number;
  JobIndex?:                   number;
  LimitBreak1?:                number;
  LimitBreak2?:                number;
  LimitBreak3?:                number;
  ModifierDexterity?:          number;
  ModifierHitPoints?:          number;
  ModifierIntelligence?:       number;
  ModifierManaPoints?:         number;
  ModifierMind?:               number;
  ModifierPiety?:              number;
  ModifierStrength?:           number;
  ModifierVitality?:           number;
  MonsterNote?:                number;
  NameEnglish?:                string;
  NameEnglish_de?:             string;
  NameEnglish_en?:             string;
  NameEnglish_fr?:             string;
  NameEnglish_ja?:             string;
  PartyBonus?:                 number;
  Prerequisite?:               number;
  PrimaryStat?:                number;
  RelicQuest?:                 number;
  Role?:                       number;
  StartingLevel?:              number;
  StartingTown?:               number;
  UIPriority?:                 number;
  UnlockQuest?:                number;
  Body?:                       number;
  Ears?:                       number;
  Feet?:                       number;
  FingerL?:                    number;
  FingerR?:                    number;
  Gloves?:                     number;
  Head?:                       number;
  Legs?:                       number;
  MainHand?:                   number;
  Neck?:                       number;
  OffHand?:                    string;
  SoulCrystal?:                number;
  Waist?:                      number;
  Wrists?:                     number;
  AdditionalData?:             number;
  Adjective?:                  number;
  AetherialReduce?:            number;
  AlwaysCollectable?:          number;
  Article?:                    number;
  BaseParam0?:                 number;
  BaseParam1?:                 number;
  BaseParam2?:                 number;
  BaseParam3?:                 number;
  BaseParam4?:                 number;
  BaseParam5?:                 number;
  BaseParamModifier?:          number;
  BaseParamSpecial0?:          number;
  BaseParamSpecial1?:          number;
  BaseParamSpecial2?:          number;
  BaseParamSpecial3?:          number;
  BaseParamSpecial4?:          number;
  BaseParamSpecial5?:          number;
  BaseParamValue0?:            number;
  BaseParamValue1?:            number;
  BaseParamValue2?:            number;
  BaseParamValue3?:            number;
  BaseParamValue4?:            number;
  BaseParamValue5?:            number;
  BaseParamValueSpecial0?:     number;
  BaseParamValueSpecial1?:     number;
  BaseParamValueSpecial2?:     number;
  BaseParamValueSpecial3?:     number;
  BaseParamValueSpecial4?:     number;
  BaseParamValueSpecial5?:     number;
  Block?:                      number;
  BlockRate?:                  number;
  CanBeHq?:                    number;
  ClassJobRepair?:             number;
  ClassJobUse?:                number;
  CooldownS?:                  number;
  DamageMag?:                  number;
  DamagePhys?:                 number;
  DefenseMag?:                 number;
  DefensePhys?:                number;
  DelayMs?:                    number;
  Desynth?:                    number;
  EquipRestriction?:           number;
  EquipSlotCategory?:          number;
  FilterGroup?:                number;
  GrandCompany?:               number;
  IconID?:                     number;
  IsAdvancedMeldingPermitted?: number;
  IsCollectable?:              number;
  IsCrestWorthy?:              number;
  IsDyeable?:                  number;
  IsGlamourous?:               number;
  IsIndisposable?:             number;
  IsPvP?:                      number;
  IsUnique?:                   number;
  IsUntradable?:               number;
  ItemAction?:                 number;
  ItemGlamour?:                number;
  ItemRepair?:                 number;
  ItemSearchCategory?:         number;
  ItemSeries?:                 number;
  ItemSortCatgegory?:          number;
  ItemSpecialBonus?:           number;
  ItemSpecialBonusParam?:      number;
  ItemUICategory?:             number;
  LevelEquip?:                 number;
  LevelItem?:                  number;
  Lot?:                        number;
  MateriaSlotCount?:           number;
  MaterializeType?:            number;
  ModelMain?:                  Model;
  ModelSub?:                   Model;
  Plural?:                     Plural;
  Plural_de?:                  PluralDe;
  Plural_en?:                  Plural;
  Plural_fr?:                  PluralFr;
  Plural_ja?:                  string;
  PossessivePronoun?:          number;
  PriceLow?:                   number;
  PriceMid?:                   number;
  Pronoun?:                    number;
  Rarity?:                     number;
  Singular?:                   Singular;
  Singular_de?:                SingularDe;
  Singular_en?:                Singular;
  Singular_fr?:                SingularFr;
  Singular_ja?:                SingularJa;
  StackSize?:                  number;
  StartsWithVowel?:            number;
  Category?:                   number;
  ClassJob?:                   number;
  Order?:                      number;
  OrderMajor?:                 number;
  OrderMinor?:                 number;
  DataType?:                   number;
  JournalSection?:             number;
  SeparateType?:               number;
  DiscoveryArrayByte?:         number;
  DiscoveryFlag?:              number;
  DiscoveryIndex?:             number;
  Hierarchy?:                  number;
  IsEvent?:                    number;
  MapCondition?:               number;
  MapFilename?:                MapFilename;
  MapFilenameId?:              MapFilenameID;
  MapIndex?:                   number;
  MapMarkerRange?:             number;
  OffsetX?:                    number;
  OffsetY?:                    number;
  PlaceName?:                  number;
  PlaceNameRegion?:            number;
  PlaceNameSub?:               number;
  PriorityCategoryUI?:         number;
  PriorityUI?:                 number;
  SizeFactor?:                 number;
  TerritoryType?:              number;
  AchievementIndex?:           number;
  "AddedIn5-3"?:               number;
  Aetheryte?:                  number;
  ArrayEventHandler?:          number;
  BGM?:                        number;
  BattalionMode?:              number;
  Bg?:                         Bg;
  Bg_en?:                      Bg;
  ExVersion?:                  number;
  ExclusiveType?:              number;
  FixedTime?:                  string;
  IsPvpZone?:                  number;
  LoadingImage?:               number;
  Map?:                        number;
  Mount?:                      number;
  MountSpeed?:                 number;
  PCSearch?:                   number;
  PlaceNameIcon?:              PlaceNameIcon;
  PlaceNameIconID?:            number;
  PlaceNameRegionIcon?:        Quest0PlaceNameRegionIcon;
  PlaceNameRegionIconID?:      number;
  PlaceNameZone?:              number;
  QuestBattle?:                number;
  Resident?:                   number;
  Stealth?:                    number;
  TerritoryIntendedUse?:       number;
  WeatherRate?:                number;
}

export interface Quest10Class {
  "1HWpn%"?:                   number;
  "2HWpn%"?:                   number;
  "Bracelet%"?:                number;
  "Chest%"?:                   number;
  "ChestHead%"?:               number;
  "ChestHeadLegsFeet%"?:       number;
  "ChestLegsFeet%"?:           number;
  "ChestLegsGloves%"?:         number;
  Description?:                string;
  Description_de?:             string;
  Description_en?:             string;
  Description_fr?:             string;
  Description_ja?:             string;
  "Earring%"?:                 number;
  "Feet%"?:                    number;
  "Hands%"?:                   number;
  "Head%"?:                    number;
  "HeadChestHandsLegsFeet%"?:  number;
  ID:                          number;
  "Legs%"?:                    number;
  "LegsFeet%"?:                number;
  MeldParam0?:                 number;
  MeldParam1?:                 number;
  MeldParam10?:                number;
  MeldParam11?:                number;
  MeldParam12?:                number;
  MeldParam2?:                 number;
  MeldParam3?:                 number;
  MeldParam4?:                 number;
  MeldParam5?:                 number;
  MeldParam6?:                 number;
  MeldParam7?:                 number;
  MeldParam8?:                 number;
  MeldParam9?:                 number;
  Name?:                       string;
  Name_de?:                    string;
  Name_en?:                    string;
  Name_fr?:                    string;
  Name_ja?:                    string;
  "Necklace%"?:                number;
  "OH%"?:                      number;
  OrderPriority?:              number;
  PacketIndex?:                number;
  "Ring%"?:                    number;
  "UnderArmor%"?:              number;
  "Waist%"?:                   number;
  ACN?:                        number;
  ADV?:                        number;
  ALC?:                        number;
  ARC?:                        number;
  ARM?:                        number;
  AST?:                        number;
  BLM?:                        number;
  BLU?:                        number;
  BRD?:                        number;
  BSM?:                        number;
  BTN?:                        number;
  CNJ?:                        number;
  CRP?:                        number;
  CUL?:                        number;
  DNC?:                        number;
  DRG?:                        number;
  DRK?:                        number;
  FSH?:                        number;
  GLA?:                        number;
  GNB?:                        number;
  GSM?:                        number;
  LNC?:                        number;
  LTW?:                        number;
  MCH?:                        number;
  MIN?:                        number;
  MNK?:                        number;
  MRD?:                        number;
  NIN?:                        number;
  PGL?:                        number;
  PLD?:                        number;
  RDM?:                        number;
  ROG?:                        number;
  SAM?:                        number;
  SCH?:                        number;
  SMN?:                        number;
  THM?:                        number;
  WAR?:                        number;
  WHM?:                        number;
  WVR?:                        number;
  Abbreviation?:               string;
  Abbreviation_de?:            string;
  Abbreviation_en?:            string;
  Abbreviation_fr?:            string;
  Abbreviation_ja?:            string;
  BattleClassIndex?:           string;
  CanQueueForDuty?:            number;
  ClassJobCategory?:           number;
  ClassJobParent?:             number;
  ExpArrayIndex?:              number;
  Icon?:                       string;
  IsLimitedJob?:               number;
  ItemSoulCrystal?:            number;
  ItemStartingWeapon?:         number;
  JobIndex?:                   number;
  LimitBreak1?:                number;
  LimitBreak2?:                number;
  LimitBreak3?:                number;
  ModifierDexterity?:          number;
  ModifierHitPoints?:          number;
  ModifierIntelligence?:       number;
  ModifierManaPoints?:         number;
  ModifierMind?:               number;
  ModifierPiety?:              number;
  ModifierStrength?:           number;
  ModifierVitality?:           number;
  MonsterNote?:                number;
  NameEnglish?:                string;
  NameEnglish_de?:             string;
  NameEnglish_en?:             string;
  NameEnglish_fr?:             string;
  NameEnglish_ja?:             string;
  PartyBonus?:                 number;
  Prerequisite?:               number;
  PrimaryStat?:                number;
  RelicQuest?:                 number;
  Role?:                       number;
  StartingLevel?:              number;
  StartingTown?:               number;
  UIPriority?:                 number;
  UnlockQuest?:                number;
  Body?:                       number;
  Ears?:                       number;
  Feet?:                       number;
  FingerL?:                    number;
  FingerR?:                    number;
  Gloves?:                     number;
  Head?:                       number;
  Legs?:                       number;
  MainHand?:                   number;
  Neck?:                       number;
  OffHand?:                    number;
  SoulCrystal?:                number;
  Waist?:                      number;
  Wrists?:                     number;
  AdditionalData?:             number;
  Adjective?:                  number;
  AetherialReduce?:            number;
  AlwaysCollectable?:          number;
  Article?:                    number;
  BaseParam0?:                 number;
  BaseParam1?:                 number;
  BaseParam2?:                 number;
  BaseParam3?:                 number;
  BaseParam4?:                 number;
  BaseParam5?:                 number;
  BaseParamModifier?:          number;
  BaseParamSpecial0?:          number;
  BaseParamSpecial1?:          number;
  BaseParamSpecial2?:          number;
  BaseParamSpecial3?:          number;
  BaseParamSpecial4?:          number;
  BaseParamSpecial5?:          number;
  BaseParamValue0?:            number;
  BaseParamValue1?:            number;
  BaseParamValue2?:            number;
  BaseParamValue3?:            number;
  BaseParamValue4?:            number;
  BaseParamValue5?:            number;
  BaseParamValueSpecial0?:     number;
  BaseParamValueSpecial1?:     number;
  BaseParamValueSpecial2?:     number;
  BaseParamValueSpecial3?:     number;
  BaseParamValueSpecial4?:     number;
  BaseParamValueSpecial5?:     number;
  Block?:                      number;
  BlockRate?:                  number;
  CanBeHq?:                    number;
  ClassJobRepair?:             number;
  ClassJobUse?:                number;
  CooldownS?:                  number;
  DamageMag?:                  number;
  DamagePhys?:                 number;
  DefenseMag?:                 number;
  DefensePhys?:                number;
  DelayMs?:                    number;
  Desynth?:                    number;
  EquipRestriction?:           number;
  EquipSlotCategory?:          number;
  FilterGroup?:                number;
  GrandCompany?:               number;
  IconID?:                     number;
  IsAdvancedMeldingPermitted?: number;
  IsCollectable?:              number;
  IsCrestWorthy?:              number;
  IsDyeable?:                  number;
  IsGlamourous?:               number;
  IsIndisposable?:             number;
  IsPvP?:                      number;
  IsUnique?:                   number;
  IsUntradable?:               number;
  ItemAction?:                 number;
  ItemGlamour?:                number;
  ItemRepair?:                 number;
  ItemSearchCategory?:         number;
  ItemSeries?:                 number;
  ItemSortCatgegory?:          number;
  ItemSpecialBonus?:           number;
  ItemSpecialBonusParam?:      number;
  ItemUICategory?:             number;
  LevelEquip?:                 number;
  LevelItem?:                  number;
  Lot?:                        number;
  MateriaSlotCount?:           number;
  MaterializeType?:            number;
  ModelMain?:                  Model;
  ModelSub?:                   Model;
  Plural?:                     Plural;
  Plural_de?:                  PluralDe;
  Plural_en?:                  Plural;
  Plural_fr?:                  PluralFr;
  Plural_ja?:                  string;
  PossessivePronoun?:          number;
  PriceLow?:                   number;
  PriceMid?:                   number;
  Pronoun?:                    number;
  Rarity?:                     number;
  Singular?:                   Singular;
  Singular_de?:                SingularDe;
  Singular_en?:                Singular;
  Singular_fr?:                SingularFr;
  Singular_ja?:                SingularJa;
  StackSize?:                  number;
  StartsWithVowel?:            number;
  Category?:                   number;
  ClassJob?:                   number;
  Order?:                      number;
  OrderMajor?:                 number;
  OrderMinor?:                 number;
  DataType?:                   number;
  JournalSection?:             number;
  SeparateType?:               number;
  DiscoveryArrayByte?:         number;
  DiscoveryFlag?:              number;
  DiscoveryIndex?:             number | string;
  Hierarchy?:                  number;
  IsEvent?:                    number;
  MapCondition?:               number;
  MapFilename?:                string;
  MapFilenameId?:              string;
  MapIndex?:                   number;
  MapMarkerRange?:             number;
  OffsetX?:                    number;
  OffsetY?:                    number;
  PlaceName?:                  number;
  PlaceNameRegion?:            number;
  PlaceNameSub?:               number;
  PriorityCategoryUI?:         number;
  PriorityUI?:                 number;
  SizeFactor?:                 number;
  TerritoryType?:              number;
  AchievementIndex?:           number;
  "AddedIn5-3"?:               number;
  Aetheryte?:                  number;
  ArrayEventHandler?:          number;
  BGM?:                        number;
  BattalionMode?:              number;
  Bg?:                         string;
  Bg_en?:                      string;
  ExVersion?:                  number;
  ExclusiveType?:              number;
  FixedTime?:                  string;
  IsPvpZone?:                  number;
  LoadingImage?:               number;
  Map?:                        number;
  Mount?:                      number;
  MountSpeed?:                 number;
  PCSearch?:                   number;
  PlaceNameIcon?:              string;
  PlaceNameIconID?:            number;
  PlaceNameRegionIcon?:        string;
  PlaceNameRegionIconID?:      number;
  PlaceNameZone?:              number;
  QuestBattle?:                number;
  Resident?:                   number;
  Stealth?:                    number;
  TerritoryIntendedUse?:       number;
  WeatherRate?:                number;
}

export interface Quest15Class {
  DataType?:              number;
  ID:                     number;
  JournalSection?:        number;
  Name?:                  string;
  Name_de?:               string;
  Name_en?:               string;
  Name_fr?:               string;
  Name_ja?:               string;
  SeparateType?:          number;
  DiscoveryArrayByte?:    number;
  DiscoveryFlag?:         number;
  DiscoveryIndex?:        number;
  Hierarchy?:             number;
  IsEvent?:               number;
  MapCondition?:          number;
  MapFilename?:           MapFilename;
  MapFilenameId?:         MapFilenameID;
  MapIndex?:              number;
  MapMarkerRange?:        number;
  OffsetX?:               number;
  OffsetY?:               number;
  PlaceName?:             number;
  PlaceNameRegion?:       number;
  PlaceNameSub?:          number;
  PriorityCategoryUI?:    number;
  PriorityUI?:            number;
  SizeFactor?:            number;
  TerritoryType?:         number;
  AchievementIndex?:      number;
  "AddedIn5-3"?:          number;
  Aetheryte?:             number;
  ArrayEventHandler?:     number;
  BGM?:                   number;
  BattalionMode?:         number;
  Bg?:                    Bg;
  Bg_en?:                 Bg;
  ExVersion?:             number;
  ExclusiveType?:         number;
  FixedTime?:             string;
  IsPvpZone?:             number;
  LoadingImage?:          number;
  Map?:                   number;
  Mount?:                 number;
  MountSpeed?:            number;
  PCSearch?:              number;
  PlaceNameIcon?:         PlaceNameIcon;
  PlaceNameIconID?:       number;
  PlaceNameRegionIcon?:   Quest0PlaceNameRegionIcon;
  PlaceNameRegionIconID?: number;
  PlaceNameZone?:         number;
  QuestBattle?:           number;
  Resident?:              number;
  Stealth?:               number;
  TerritoryIntendedUse?:  number;
  WeatherRate?:           number;
}

export interface Quest16Class {
  DataType?:              number;
  ID:                     number;
  JournalSection?:        number;
  Name?:                  string;
  Name_de?:               string;
  Name_en?:               string;
  Name_fr?:               string;
  Name_ja?:               string;
  SeparateType?:          number;
  DiscoveryArrayByte?:    number;
  DiscoveryFlag?:         number;
  DiscoveryIndex?:        string;
  Hierarchy?:             number;
  IsEvent?:               number;
  MapCondition?:          number;
  MapFilename?:           string;
  MapFilenameId?:         string;
  MapIndex?:              number;
  MapMarkerRange?:        number;
  OffsetX?:               number;
  OffsetY?:               number;
  PlaceName?:             number;
  PlaceNameRegion?:       number;
  PlaceNameSub?:          number;
  PriorityCategoryUI?:    number;
  PriorityUI?:            number;
  SizeFactor?:            number;
  TerritoryType?:         number;
  AchievementIndex?:      number;
  "AddedIn5-3"?:          number;
  Aetheryte?:             number;
  ArrayEventHandler?:     number;
  BGM?:                   number;
  BattalionMode?:         number;
  Bg?:                    string;
  Bg_en?:                 string;
  ExVersion?:             number;
  ExclusiveType?:         number;
  FixedTime?:             string;
  IsPvpZone?:             number;
  LoadingImage?:          number;
  Map?:                   number;
  Mount?:                 number;
  MountSpeed?:            number;
  PCSearch?:              number;
  PlaceNameIcon?:         string;
  PlaceNameIconID?:       number;
  PlaceNameRegionIcon?:   Quest16PlaceNameRegionIcon;
  PlaceNameRegionIconID?: number;
  PlaceNameZone?:         number;
  QuestBattle?:           number;
  Resident?:              number;
  Stealth?:               number;
  TerritoryIntendedUse?:  number;
  WeatherRate?:           number;
}

export enum Quest16PlaceNameRegionIcon {
  I122000122007PNG = "/i/122000/122007.png",
  I122000122008PNG = "/i/122000/122008.png",
  I122000122009PNG = "/i/122000/122009.png",
}

export interface Quest17Class {
  DataType?:              number;
  ID:                     number;
  JournalSection?:        number;
  Name?:                  string;
  Name_de?:               string;
  Name_en?:               string;
  Name_fr?:               string;
  Name_ja?:               string;
  SeparateType?:          number;
  DiscoveryArrayByte?:    number;
  DiscoveryFlag?:         number;
  DiscoveryIndex?:        number | string;
  Hierarchy?:             number;
  IsEvent?:               number;
  MapCondition?:          number;
  MapFilename?:           string;
  MapFilenameId?:         string;
  MapIndex?:              number;
  MapMarkerRange?:        number;
  OffsetX?:               number;
  OffsetY?:               number;
  PlaceName?:             number;
  PlaceNameRegion?:       number;
  PlaceNameSub?:          number;
  PriorityCategoryUI?:    number;
  PriorityUI?:            number;
  SizeFactor?:            number;
  TerritoryType?:         number;
  AchievementIndex?:      number;
  "AddedIn5-3"?:          number;
  Aetheryte?:             number;
  ArrayEventHandler?:     number;
  BGM?:                   number;
  BattalionMode?:         number;
  Bg?:                    string;
  Bg_en?:                 string;
  ExVersion?:             number;
  ExclusiveType?:         number;
  FixedTime?:             string;
  IsPvpZone?:             number;
  LoadingImage?:          number;
  Map?:                   number;
  Mount?:                 number;
  MountSpeed?:            number;
  PCSearch?:              number;
  PlaceNameIcon?:         string;
  PlaceNameIconID?:       number;
  PlaceNameRegionIcon?:   string;
  PlaceNameRegionIconID?: number;
  PlaceNameZone?:         number;
  QuestBattle?:           number;
  Resident?:              number;
  Stealth?:               number;
  TerritoryIntendedUse?:  number;
  WeatherRate?:           number;
}

export interface Quest19Class {
  DataType?:              number;
  ID:                     number;
  JournalSection?:        number;
  Name?:                  string;
  Name_de?:               string;
  Name_en?:               string;
  Name_fr?:               string;
  Name_ja?:               string;
  SeparateType?:          number;
  DiscoveryArrayByte?:    number;
  DiscoveryFlag?:         number;
  DiscoveryIndex?:        string;
  Hierarchy?:             number;
  IsEvent?:               number;
  MapCondition?:          number;
  MapFilename?:           string;
  MapFilenameId?:         string;
  MapIndex?:              number;
  MapMarkerRange?:        number;
  OffsetX?:               number;
  OffsetY?:               number;
  PlaceName?:             number;
  PlaceNameRegion?:       number;
  PlaceNameSub?:          number;
  PriorityCategoryUI?:    number;
  PriorityUI?:            number;
  SizeFactor?:            number;
  TerritoryType?:         number;
  AchievementIndex?:      number | string;
  "AddedIn5-3"?:          number;
  Aetheryte?:             number;
  ArrayEventHandler?:     number;
  BGM?:                   number;
  BattalionMode?:         number;
  Bg?:                    string;
  Bg_en?:                 string;
  ExVersion?:             number;
  ExclusiveType?:         number;
  FixedTime?:             string;
  IsPvpZone?:             number;
  LoadingImage?:          number;
  Map?:                   number;
  Mount?:                 number;
  MountSpeed?:            number;
  PCSearch?:              number;
  PlaceNameIcon?:         string;
  PlaceNameIconID?:       number | string;
  PlaceNameRegionIcon?:   string;
  PlaceNameRegionIconID?: number | string;
  PlaceNameZone?:         number;
  QuestBattle?:           number;
  Resident?:              number;
  Stealth?:               number;
  TerritoryIntendedUse?:  number;
  WeatherRate?:           number;
}

export interface Quest2Class {
  CondBattle?:            number;
  CondLv?:                number;
  CondPVP?:               number;
  CondPVPOnly?:           number;
  Data0?:                 number;
  Data1?:                 number;
  Data2?:                 number;
  Data3?:                 number;
  Data4?:                 number;
  Data5?:                 number;
  Data6?:                 number;
  Data7?:                 number;
  Data8?:                 number;
  DataHQ0?:               number;
  DataHQ1?:               number;
  DataHQ2?:               number;
  DataHQ3?:               number;
  DataHQ4?:               number;
  DataHQ5?:               number;
  DataHQ6?:               number;
  DataHQ7?:               number;
  DataHQ8?:               number;
  ID:                     number;
  Type?:                  number;
  Category?:              number;
  ClassJob?:              number;
  Icon?:                  string;
  IconID?:                number;
  Name?:                  string;
  Name_de?:               string;
  Name_en?:               string;
  Name_fr?:               string;
  Name_ja?:               string;
  Order?:                 number;
  OrderMajor?:            number;
  OrderMinor?:            number;
  DataType?:              number;
  JournalSection?:        number;
  SeparateType?:          number;
  DiscoveryArrayByte?:    number;
  DiscoveryFlag?:         number;
  DiscoveryIndex?:        number;
  Hierarchy?:             number;
  IsEvent?:               number;
  MapCondition?:          number;
  MapFilename?:           MapFilename;
  MapFilenameId?:         MapFilenameID;
  MapIndex?:              number;
  MapMarkerRange?:        number;
  OffsetX?:               number;
  OffsetY?:               number;
  PlaceName?:             number;
  PlaceNameRegion?:       number;
  PlaceNameSub?:          number;
  PriorityCategoryUI?:    number;
  PriorityUI?:            number;
  SizeFactor?:            number;
  TerritoryType?:         number;
  AchievementIndex?:      number;
  "AddedIn5-3"?:          number;
  Aetheryte?:             number;
  ArrayEventHandler?:     number;
  BGM?:                   number;
  BattalionMode?:         number;
  Bg?:                    Bg;
  Bg_en?:                 Bg;
  ExVersion?:             number;
  ExclusiveType?:         number;
  FixedTime?:             string;
  IsPvpZone?:             number;
  LoadingImage?:          number;
  Map?:                   number;
  Mount?:                 number;
  MountSpeed?:            number;
  PCSearch?:              number;
  PlaceNameIcon?:         PlaceNameIcon;
  PlaceNameIconID?:       number;
  PlaceNameRegionIcon?:   Quest0PlaceNameRegionIcon;
  PlaceNameRegionIconID?: number;
  PlaceNameZone?:         number;
  QuestBattle?:           number;
  Resident?:              number;
  Stealth?:               number;
  TerritoryIntendedUse?:  number;
  WeatherRate?:           number;
}

export interface Quest4Class {
  "1HWpn%"?:                   number;
  "2HWpn%"?:                   number;
  "Bracelet%"?:                number;
  "Chest%"?:                   number;
  "ChestHead%"?:               number;
  "ChestHeadLegsFeet%"?:       number;
  "ChestLegsFeet%"?:           number;
  "ChestLegsGloves%"?:         number;
  Description?:                string;
  Description_de?:             string;
  Description_en?:             string;
  Description_fr?:             string;
  Description_ja?:             string;
  "Earring%"?:                 number;
  "Feet%"?:                    number;
  "Hands%"?:                   number;
  "Head%"?:                    number;
  "HeadChestHandsLegsFeet%"?:  number;
  ID:                          number;
  "Legs%"?:                    number;
  "LegsFeet%"?:                number;
  MeldParam0?:                 number;
  MeldParam1?:                 number;
  MeldParam10?:                number;
  MeldParam11?:                number;
  MeldParam12?:                number;
  MeldParam2?:                 number;
  MeldParam3?:                 number;
  MeldParam4?:                 number;
  MeldParam5?:                 number;
  MeldParam6?:                 number;
  MeldParam7?:                 number;
  MeldParam8?:                 number;
  MeldParam9?:                 number;
  Name?:                       string;
  Name_de?:                    string;
  Name_en?:                    string;
  Name_fr?:                    string;
  Name_ja?:                    string;
  "Necklace%"?:                number;
  "OH%"?:                      number;
  OrderPriority?:              number;
  PacketIndex?:                number;
  "Ring%"?:                    number;
  "UnderArmor%"?:              number;
  "Waist%"?:                   number;
  ACN?:                        number;
  ADV?:                        number;
  ALC?:                        number;
  ARC?:                        number;
  ARM?:                        number;
  AST?:                        number;
  BLM?:                        number;
  BLU?:                        number;
  BRD?:                        number;
  BSM?:                        number;
  BTN?:                        number;
  CNJ?:                        number;
  CRP?:                        number;
  CUL?:                        number;
  DNC?:                        number;
  DRG?:                        number;
  DRK?:                        number;
  FSH?:                        number;
  GLA?:                        number;
  GNB?:                        number;
  GSM?:                        number;
  LNC?:                        number;
  LTW?:                        number;
  MCH?:                        number;
  MIN?:                        number;
  MNK?:                        number;
  MRD?:                        number;
  NIN?:                        number;
  PGL?:                        number;
  PLD?:                        number;
  RDM?:                        number;
  ROG?:                        number;
  SAM?:                        number;
  SCH?:                        number;
  SMN?:                        number;
  THM?:                        number;
  WAR?:                        number;
  WHM?:                        number;
  WVR?:                        number;
  Abbreviation?:               Abbreviation;
  Abbreviation_de?:            AbbreviationDe;
  Abbreviation_en?:            Abbreviation;
  Abbreviation_fr?:            AbbreviationFr;
  Abbreviation_ja?:            Abbreviation;
  BattleClassIndex?:           string;
  CanQueueForDuty?:            number;
  ClassJobCategory?:           number;
  ClassJobParent?:             number;
  ExpArrayIndex?:              number;
  Icon?:                       string;
  IsLimitedJob?:               number;
  ItemSoulCrystal?:            number;
  ItemStartingWeapon?:         number;
  JobIndex?:                   number;
  LimitBreak1?:                number;
  LimitBreak2?:                number;
  LimitBreak3?:                number;
  ModifierDexterity?:          number;
  ModifierHitPoints?:          number;
  ModifierIntelligence?:       number;
  ModifierManaPoints?:         number;
  ModifierMind?:               number;
  ModifierPiety?:              number;
  ModifierStrength?:           number;
  ModifierVitality?:           number;
  MonsterNote?:                number;
  NameEnglish?:                NameEnglish;
  NameEnglish_de?:             NameEnglish;
  NameEnglish_en?:             NameEnglish;
  NameEnglish_fr?:             NameEnglish;
  NameEnglish_ja?:             NameEnglish;
  PartyBonus?:                 number;
  Prerequisite?:               number;
  PrimaryStat?:                number;
  RelicQuest?:                 number;
  Role?:                       number;
  StartingLevel?:              number;
  StartingTown?:               number;
  UIPriority?:                 number;
  UnlockQuest?:                number;
  Body?:                       number;
  Ears?:                       number;
  Feet?:                       number;
  FingerL?:                    number;
  FingerR?:                    number;
  Gloves?:                     number;
  Head?:                       number | string;
  Legs?:                       number;
  MainHand?:                   number;
  Neck?:                       number;
  OffHand?:                    number;
  SoulCrystal?:                number;
  Waist?:                      number;
  Wrists?:                     number;
  AdditionalData?:             number;
  Adjective?:                  number;
  AetherialReduce?:            number;
  AlwaysCollectable?:          number;
  Article?:                    number;
  BaseParam0?:                 number;
  BaseParam1?:                 number;
  BaseParam2?:                 number;
  BaseParam3?:                 number;
  BaseParam4?:                 number;
  BaseParam5?:                 number;
  BaseParamModifier?:          number;
  BaseParamSpecial0?:          number;
  BaseParamSpecial1?:          number;
  BaseParamSpecial2?:          number;
  BaseParamSpecial3?:          number;
  BaseParamSpecial4?:          number;
  BaseParamSpecial5?:          number;
  BaseParamValue0?:            number;
  BaseParamValue1?:            number;
  BaseParamValue2?:            number;
  BaseParamValue3?:            number;
  BaseParamValue4?:            number;
  BaseParamValue5?:            number;
  BaseParamValueSpecial0?:     number;
  BaseParamValueSpecial1?:     number;
  BaseParamValueSpecial2?:     number;
  BaseParamValueSpecial3?:     number;
  BaseParamValueSpecial4?:     number;
  BaseParamValueSpecial5?:     number;
  Block?:                      number;
  BlockRate?:                  number;
  CanBeHq?:                    number;
  ClassJobRepair?:             number;
  ClassJobUse?:                number;
  CooldownS?:                  number;
  DamageMag?:                  number;
  DamagePhys?:                 number;
  DefenseMag?:                 number;
  DefensePhys?:                number;
  DelayMs?:                    number;
  Desynth?:                    number;
  EquipRestriction?:           number;
  EquipSlotCategory?:          number;
  FilterGroup?:                number;
  GrandCompany?:               number;
  IconID?:                     number;
  IsAdvancedMeldingPermitted?: number;
  IsCollectable?:              number;
  IsCrestWorthy?:              number;
  IsDyeable?:                  number;
  IsGlamourous?:               number;
  IsIndisposable?:             number;
  IsPvP?:                      number;
  IsUnique?:                   number;
  IsUntradable?:               number;
  ItemAction?:                 number;
  ItemGlamour?:                number;
  ItemRepair?:                 number;
  ItemSearchCategory?:         number;
  ItemSeries?:                 number;
  ItemSortCatgegory?:          number;
  ItemSpecialBonus?:           number;
  ItemSpecialBonusParam?:      number;
  ItemUICategory?:             number;
  LevelEquip?:                 number;
  LevelItem?:                  number;
  Lot?:                        number;
  MateriaSlotCount?:           number;
  MaterializeType?:            number;
  ModelMain?:                  Model;
  ModelSub?:                   Model;
  Plural?:                     Plural;
  Plural_de?:                  PluralDe;
  Plural_en?:                  Plural;
  Plural_fr?:                  PluralFr;
  Plural_ja?:                  string;
  PossessivePronoun?:          number;
  PriceLow?:                   number;
  PriceMid?:                   number;
  Pronoun?:                    number;
  Rarity?:                     number;
  Singular?:                   Singular;
  Singular_de?:                SingularDe;
  Singular_en?:                Singular;
  Singular_fr?:                SingularFr;
  Singular_ja?:                SingularJa;
  StackSize?:                  number;
  StartsWithVowel?:            number;
  Category?:                   number;
  ClassJob?:                   number;
  Order?:                      number;
  OrderMajor?:                 number;
  OrderMinor?:                 number;
  DataType?:                   number;
  JournalSection?:             number;
  SeparateType?:               number;
  DiscoveryArrayByte?:         number;
  DiscoveryFlag?:              number;
  DiscoveryIndex?:             number;
  Hierarchy?:                  number;
  IsEvent?:                    number;
  MapCondition?:               number;
  MapFilename?:                MapFilename;
  MapFilenameId?:              MapFilenameID;
  MapIndex?:                   number;
  MapMarkerRange?:             number;
  OffsetX?:                    number;
  OffsetY?:                    number;
  PlaceName?:                  number;
  PlaceNameRegion?:            number;
  PlaceNameSub?:               number;
  PriorityCategoryUI?:         number;
  PriorityUI?:                 number;
  SizeFactor?:                 number;
  TerritoryType?:              number;
  AchievementIndex?:           number;
  "AddedIn5-3"?:               number;
  Aetheryte?:                  number;
  ArrayEventHandler?:          number;
  BGM?:                        number;
  BattalionMode?:              number;
  Bg?:                         Bg;
  Bg_en?:                      Bg;
  ExVersion?:                  number;
  ExclusiveType?:              number;
  FixedTime?:                  string;
  IsPvpZone?:                  number;
  LoadingImage?:               number;
  Map?:                        number;
  Mount?:                      number;
  MountSpeed?:                 number;
  PCSearch?:                   number;
  PlaceNameIcon?:              PlaceNameIcon;
  PlaceNameIconID?:            number;
  PlaceNameRegionIcon?:        Quest0PlaceNameRegionIcon;
  PlaceNameRegionIconID?:      number;
  PlaceNameZone?:              number;
  QuestBattle?:                number;
  Resident?:                   number;
  Stealth?:                    number;
  TerritoryIntendedUse?:       number;
  WeatherRate?:                number;
}

export interface Quest7Class {
  ID:                        number;
  Name?:                     number | string;
  Name_de?:                  string;
  Name_en?:                  string;
  Name_fr?:                  string;
  Name_ja?:                  string;
  ActionTimelineIDMode?:     number;
  IsLoop?:                   number;
  IsMotionCanceledByMoving?: number;
  Key?:                      string;
  Key_en?:                   string;
  KillUpper?:                number;
  LoadType?:                 number;
  LookAtMode?:               number;
  Pause?:                    number;
  Priority?:                 number;
  Resident?:                 number;
  ResidentPap?:              number;
  Slot?:                     number;
  Stance?:                   number;
  StartAttach?:              number;
  Type?:                     number;
  WeaponTimeline?:           number;
  VFX?:                      number;
  ACN?:                      number;
  ADV?:                      number;
  ALC?:                      number;
  ARC?:                      number;
  ARM?:                      number;
  AST?:                      number;
  BLM?:                      number;
  BLU?:                      number;
  BRD?:                      number;
  BSM?:                      number;
  BTN?:                      number;
  CNJ?:                      number;
  CRP?:                      number;
  CUL?:                      number;
  DNC?:                      number;
  DRG?:                      number;
  DRK?:                      number;
  FSH?:                      number;
  GLA?:                      number;
  GNB?:                      number;
  GSM?:                      number;
  LNC?:                      number;
  LTW?:                      number;
  MCH?:                      number;
  MIN?:                      number;
  MNK?:                      number;
  MRD?:                      number;
  NIN?:                      number;
  PGL?:                      number;
  PLD?:                      number;
  RDM?:                      number;
  ROG?:                      number;
  SAM?:                      number;
  SCH?:                      number;
  SMN?:                      number;
  THM?:                      number;
  WAR?:                      number;
  WHM?:                      number;
  WVR?:                      number;
  DataType?:                 number;
  JournalSection?:           number;
  SeparateType?:             number;
  DiscoveryArrayByte?:       number;
  DiscoveryFlag?:            number;
  DiscoveryIndex?:           number | string;
  Hierarchy?:                number;
  IsEvent?:                  number;
  MapCondition?:             number;
  MapFilename?:              string;
  MapFilenameId?:            string;
  MapIndex?:                 number;
  MapMarkerRange?:           number;
  OffsetX?:                  number;
  OffsetY?:                  number;
  PlaceName?:                number;
  PlaceNameRegion?:          number;
  PlaceNameSub?:             number;
  PriorityCategoryUI?:       number;
  PriorityUI?:               number;
  SizeFactor?:               number;
  TerritoryType?:            number;
  AchievementIndex?:         number;
  "AddedIn5-3"?:             number;
  Aetheryte?:                number;
  ArrayEventHandler?:        number;
  BGM?:                      number;
  BattalionMode?:            number;
  Bg?:                       string;
  Bg_en?:                    string;
  ExVersion?:                number;
  ExclusiveType?:            number;
  FixedTime?:                string;
  IsPvpZone?:                number;
  LoadingImage?:             number;
  Map?:                      number;
  Mount?:                    number;
  MountSpeed?:               number;
  PCSearch?:                 number;
  PlaceNameIcon?:            string;
  PlaceNameIconID?:          number;
  PlaceNameRegionIcon?:      string;
  PlaceNameRegionIconID?:    number;
  PlaceNameZone?:            number;
  QuestBattle?:              number;
  Stealth?:                  number;
  TerritoryIntendedUse?:     number;
  WeatherRate?:              number;
}
